# .swiftlint.yml

# Paths to include (optional)
included:
  - Sources
  - Tests

# Paths to exclude (optional)
excluded:
  - Pods
  - Carthage
  - Build

# Disabled rules (optional)
disabled_rules:
  - line_length

# Custom rules (optional)
custom_rules:
  my_custom_rule:
    included: ".*.swift"
    name: "My custom rule"
    regex: '.*'
    message: "This is a custom rule"
    severity: warning
